import { useState } from "react";
import Head from "next/head";
import CareerBag from "../components/CareerBag";
import {
  ColorSchemeProvider,
  MantineProvider,
  ColorScheme,
} from "@mantine/core";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  const [colorScheme, setColorScheme] = useState<ColorScheme>("dark");
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === "dark" ? "light" : "dark"));
  return (
    <div>
      <Head>
        <title>Career Bag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <ColorSchemeProvider
          colorScheme={colorScheme}
          toggleColorScheme={toggleColorScheme}
        >
          <MantineProvider
            theme={{ colorScheme }}
            withGlobalStyles
            withNormalizeCSS
          >
            <Header
              colorScheme={colorScheme}
              toggleColorScheme={toggleColorScheme}
            />
            <CareerBag />
            <Footer />
          </MantineProvider>
        </ColorSchemeProvider>
      </main>
    </div>
  );
}
